config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :posts
  resources :users

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end


  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "main"
	def index
		@posts = Post.all.limit(3).order('created_at desc')
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_admin!, except: [:show, :index]
	def index
		@posts = Post.all.order('created_at desc')
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Welcome to Morder Design
		</h1>
	</div>
	<% @posts.each do |post| %>
		<div class="col-md-4">
			<img class="img-circle img-center" src="http://lorempixel.com/140/140/" alt="???">
			<h2 class="text-center"><%= link_to post.title, post %></h2>
			<p class="text-center"><%= post.content.truncate(400) %></p>
		</div>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<hr>
<footer>
	<div class="row">
		<div class="col-lg-12">
			<p class = 'pull-right'>
				<% if admin_signed_in? %>
					Здравствуйте, <%= current_admin.email %> | <%= link_to 'Выйти', destroy_admin_session_path, :method => :delete %> | <%= link_to 'Создать пост', new_post_path %>
				<% else %>
					<%= link_to 'Войти', new_admin_session_path %>
				<% end %>
			</p>
			<p>Copyright &copy; Your Website 2014</p>
		</div>
	</div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_message.html.erb
<% flash.each do %>
	<% if notice != nil %>
		<div class="alert alert-success fade in" role="alert">
			<%= notice %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  			<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<% end %>
	<% if alert != nil %>
		<div class="alert alert-danger fade in" role="alert">
			<%= alert %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  			<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<% end %>
<% end %>

app/views/layouts/_slider.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-example-generic" data-slide-to="1"></li>
		<li data-target="#carousel-example-generic" data-slide-to="2"></li>
	</ol>

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<%= image_tag('http://lorempixel.com/1920/700/', class: 'image-slider') %>
			<div class="carousel-caption">
			</div>
		</div>
		<div class="item">
			<%= image_tag('http://lorempixel.com/1920/700/', class: 'image-slider') %>
			<div class="carousel-caption">
			</div>
		</div>
		<div class="item">
			<%= image_tag('http://lorempixel.com/1920/700/', class: 'image-slider') %>
			<div class="carousel-caption">
			</div>
		</div>
	</div>

	<!-- Controls -->
	<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

app/views/layouts/_top.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<%= link_to image_tag('logo(white).svg', size: '50', class: 'img-center'), root_path %>
	</div><!-- /.container-fluid -->
</nav>
<nav class="navbar navbar-default navbar-fixed-top nav-2">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'Morder Design', root_path, class: 'navbar-brand' %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#">Link</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Action</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
					</ul>
				</li>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<%= render 'layouts/head' %>
	<body>
		<%= render 'layouts/top' %>
		<%= render 'layouts/message' %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
	<%= render 'layouts/head' %>
	<body>
		<%= render 'layouts/top' %>
		<%= render 'layouts/message' %>
		<%= render 'layouts/slider' %>
		<div class="container">
			<%= yield %>
		</div>


		<a id="firmsonmap_biglink" href="http://2gis.ru/tyumen/profiles/1830115630099768,1830115630181359,1830115630181358,1830115630181357,1830115630181360/center/65.5902671813965,57.120959419875106/zoom/13">Перейти к большой карте</a><script charset="utf-8" src="http://widgets.2gis.com/js/DGWidgetLoader.js"></script><script charset="utf-8">new DGWidgetLoader({"height":400,"pos":{"lat":57.120959419875106,"lon":65.5902671813965,"zoom":12},"opt":{"city":"tyumen"},"org":[{"id":"1830115630099768"},{"id":"1830115630181359"},{"id":"1830115630181358"},{"id":"1830115630181357"},{"id":"1830115630181360"}]});</script>
		<noscript style="color:#c00;font-size:16px;font-weight:bold;">Виджет карты использует JavaScript. Включите его в настройках вашего браузера.</noscript>


		<script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=qAxyqfEAMBuFc4c6-x1imShREWqbUgRm&height=400"></script>


		<div class="container">
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
<p>
	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
</p>
<p>
	<%= f.label :content %>
	<%= f.text_area :content, class: 'form-control', rows: '5' %>
</p>
<p>
	<%= f.file_field :image %>
</p>
	<%= f.submit "Save post", class: "btn btn-lg btn-primary btn-block" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<p><%=link_to 'Back', root_path%></p>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<h2><%= link_to post.title, post %></h2>
	<h4><%= post.content.truncate(400) %></h4>
	<h6><%= post.created_at.strftime("%B, %d, %Y") %></h6>
	<hr>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<p><%=link_to 'Back', root_path%></p>

app/views/posts/show.html.erb
<div id='post-show'>
	<h2><%= @post.title %></h2>
	<hr>
	<img class = 'img-center img-rounded img-responsive' src="http://lorempixel.com/750/400/" alt="???">
	<p><%= @post.content %></p>
	<small><%= @post.created_at.strftime('%B %d, %Y') %></small>
	<p>
		<%=link_to 'Back', root_path%> 
		<% if admin_signed_in? %>
			| <%= link_to 'Edit', edit_post_path(@post) %>
			| <%= link_to 'Destroy', post_path, method: :delete, data: {confirm: 'Are you sure?'} %>
		<% end %>
	</p>
</div>